FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-lock.yaml package.json ./
RUN pnpm install

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]
