// ─── Error Codes ────────────────────────────
// Formato: DOMAIN_ERROR_DESCRIPTION

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',

  // Companies
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  COMPANY_TAX_ID_EXISTS: 'COMPANY_TAX_ID_EXISTS',
  COMPANY_NOT_VERIFIED: 'COMPANY_NOT_VERIFIED',
  COMPANY_SUSPENDED: 'COMPANY_SUSPENDED',

  // Subscriptions
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_LIMIT_REACHED: 'SUBSCRIPTION_LIMIT_REACHED',

  // Plans
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_FEATURE_NOT_AVAILABLE: 'PLAN_FEATURE_NOT_AVAILABLE',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',

  // Shipments
  SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
  SHIPMENT_INVALID_TRANSITION: 'SHIPMENT_INVALID_TRANSITION',
  SHIPMENT_ALREADY_ASSIGNED: 'SHIPMENT_ALREADY_ASSIGNED',

  // Trucks
  TRUCK_NOT_FOUND: 'TRUCK_NOT_FOUND',
  TRUCK_NOT_AVAILABLE: 'TRUCK_NOT_AVAILABLE',
  TRUCK_PLATE_EXISTS: 'TRUCK_PLATE_EXISTS',

  // Drivers
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DRIVER_NOT_AVAILABLE: 'DRIVER_NOT_AVAILABLE',
  DRIVER_LICENSE_EXPIRED: 'DRIVER_LICENSE_EXPIRED',

  // Relationships
  RELATIONSHIP_NOT_FOUND: 'RELATIONSHIP_NOT_FOUND',
  RELATIONSHIP_ALREADY_EXISTS: 'RELATIONSHIP_ALREADY_EXISTS',
  RELATIONSHIP_SELF_REQUEST: 'RELATIONSHIP_SELF_REQUEST',

  // Expenses
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  EXPENSE_ALREADY_PROCESSED: 'EXPENSE_ALREADY_PROCESSED',

  // Files
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Generic
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
