export enum NotificationType {
  SHIPMENT_STATUS = 'shipment_status',
  SHIPMENT_PROPOSED = 'shipment_proposed',
  SHIPMENT_ACCEPTED = 'shipment_accepted',
  SHIPMENT_REJECTED = 'shipment_rejected',
  SHIPMENT_CANCELLED = 'shipment_cancelled',
  MESSAGE_NEW = 'message_new',
  PROPOSAL_RECEIVED = 'proposal_received',
  EXPENSE_APPROVED = 'expense_approved',
  VERIFICATION_UPDATE = 'verification_update',
  SUBSCRIPTION_ALERT = 'subscription_alert',
  DRIVER_LOCATION = 'driver_location',
  PROXIMITY_ALERT = 'proximity_alert',
  RUN_ASSIGNED = 'run_assigned',
  EXPENSE_CREATED = 'expense_created',
  SYSTEM = 'system',
}
